django/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<subject_id>[a-zA-Z0-9]{1,7})$', views.view_assignment, name='view'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^check-response/(?P<submission_id>[0-9]{1,})/$', views.check_response, name='check_response'),
    url(r'^report/(?P<assignment>[0-9]{1,})$', views.report, name='report'),
]

django/webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User


def index(request):
    # return render(request, 'marketing/index.html')
    return redirect('dashboard:index')


def register_view(request):
    return render(request, 'marketing/signup.html')


def register_user(request):
    check_user = User.objects.filter(username=request.POST.get('username', ''))
    if check_user:
        messages.error(request, 'That user already exists!')
        return redirect('signup')

    if request.POST.get('password', None) and request.POST.get('username', None):
        username = request.POST.get('username', '')
        user = User.objects.create_user(username, username + '@buffalo.edu', request.POST.get('password', ''))
        user.save()
        user = authenticate(username=user.username, password=request.POST.get('password', ''))
        if user:
            login(request, user)
            return redirect('dashboard:settings')
    messages.error(request, 'Something went wrong!')
    return redirect('signup')


def login_view(request):
    if not request.user.username in ['', None]:
        return redirect('dashboard:index')
    return render(request, 'marketing/login.html')


def login_controller(request):
    user = authenticate(username=request.POST.get('username', ''), password=request.POST.get('password', ''))
    if user:
        login(request, user)
        return redirect('dashboard:index')
    return redirect('login')


def logout_view(request):
    logout(request)
    return redirect('index')


def contact(request):
    message = "Name: " + request.POST.get('name', '') + " " + request.POST.get('surname', '') + "\n"
    message += "Email: " + request.POST.get('email', '') + "\n"
    message += "\n" + request.POST.get('message', '')

    send_mail('UB CSE Contact', message, 'email', ['to_email'])
    return redirect('index')


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^login/$', login_view, name='login'),
    url(r'^signup/$', register_view, name='signup'),
    url(r'^signup/complete/$', register_user, name='register_user'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^login/user/$', login_controller, name='login_user'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^view/', include('dashboard.urls', namespace='dashboard')),
]

django/dashboard/models.py
from django.db import models

# Create your models here.

django/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from time import sleep
from lib.ajax import response
from lib.background import grade_request
from lib.files import unzip_file
from main.models import Subject, Submission, Assignment, Report
from webapp.settings import UPLOAD_DIRECTORY
from django.contrib import messages

title = "Dashboard"


def view_assignment(request, subject_id):
    subject = Subject.objects.filter(shortcode=str(subject_id)).first()
    small = subject.name
    latest = None
    if subject.latest_assignment is not None:
        latest = subject.latest_assignment
        print(latest.name)
    return render(request, 'dashboard/view_class.html', {'title': title, 'small': small, 'latest': latest,
                                                         'subject': subject,})


def submit(request):
    if not request.user.is_authenticated:
        return response('You must be logged in!')
    password = request.POST.get('submit-password', '')
    assignment = Assignment.objects.filter(id=int(request.POST.get('assignment', '0'))).first()
    username = request.POST.get('submit-name', '')
    user = User.objects.filter(email=request.POST.get('submit-username', '')).first()
    if not user:
        return response("No user is found with that username to associate the submission to!")
    print(user.username)
    subject_id = request.POST.get('subject_id', '')
    if not user.check_password(password):
        return response("Your password was incorrect!")
    file = request.FILES['docfile']
    print(str(file))
    if str(file).endswith('.zip') or str(file).endswith('tar'):
        output = unzip_file(file, request.user.username, subject_id + '/' + assignment.shortcode)
        submission = Submission.objects.create(assignment=assignment, anon_name=username,
                                               user=user, directory_location=output)
        submission.save()
        print("First: " + str(submission.id))
        # Get Queue and send task to it
        grade_request(submission.id)
        # django_rq.enqueue(grade_request, submission_id=submission.id)

        return response("Your name has been added to the queue, please wait...", object_id=submission.id)
    return response('The file uploaded was not .zip or .tar')


def check_response(request, submission_id):
    block = True
    sleep(1)
    while block:
        submission = Submission.objects.filter(id=submission_id).first()
        if submission.was_graded:
            block = False
            # Send back response details
        print('Ugh, waiting')
        sleep(1)

    # Set up message return
    message = "Grade: " + str(submission.grade) + " out of " + str(submission.assignment.max_grade) + "<br />"
    message += "Run time: " + str(submission.efficiency) + ' seconds.<br/><br/>'
    message += "Feedback: " + submission.feedback
    return response(message)


def report(request, assignment):
    assignment = Assignment.objects.filter(id=int(assignment)).first()
    report = Report.objects.create(assignment=assignment)
    report.save()
    return redirect('dashboard:index')

django/templates/dashboard/layout.html
<!DOCTYPE html>
<html>
<head>
    {% load static from staticfiles %}
    <meta charset="UTF-8">
    <title>UB CSE Management</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- bootstrap 3.0.2 -->
    <link href="{% static 'dash/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- font Awesome -->
    <link href="{% static 'dash/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Ionicons -->
    <link href="{% static 'dash/css/ionicons.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Morris chart -->
    <link href="{% static 'dash/css/morris/morris.css' %}" rel="stylesheet" type="text/css"/>
    <!-- jvectormap -->
    <link href="{% static 'dash/css/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css"/>
    <!-- fullCalendar -->
    <link href="{% static 'dash/css/fullcalendar/fullcalendar.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Daterange picker -->
    <link href="{% static 'dash/css/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Theme style -->
    <link href="{% static 'dash/css/AdminLTE.css' %}" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
</head>
<body class="skin-blue">
<!-- header logo: style can be found in header.less -->
<div class="wrapper">

    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ title }}
                <small>{{ small }}</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            {% block content %} {% endblock %}
        </section>
        <!-- /.content -->
    </aside>
    <!-- /.right-side -->
</div>
<!-- ./wrapper -->

<!-- add new calendar event modal -->


<!-- jQuery 2.0.2 -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- jQuery UI 1.10.3 -->
<script src="{% static 'dash/js/jquery-ui-1.10.3.min.js' %}" type="text/javascript"></script>
<!-- Bootstrap -->
<script src="{% static 'dash/js/bootstrap.min.js' %}" type="text/javascript"></script>
<!-- Morris.js charts -->
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{% static 'dash/js/plugins/morris/morris.min.js' %}" type="text/javascript"></script>
<!-- Sparkline -->
<script src="{% static 'dash/js/plugins/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
<!-- jvectormap -->
<script src="{% static 'dash/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dash/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"
        type="text/javascript"></script>
<!-- fullCalendar -->
<script src="{% static 'dash/js/plugins/fullcalendar/fullcalendar.min.js' %}" type="text/javascript"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dash/js/plugins/jqueryKnob/jquery.knob.js' %}" type="text/javascript"></script>
<!-- daterangepicker -->
<script src="{% static 'dash/js/plugins/daterangepicker/daterangepicker.js' %}" type="text/javascript"></script>
<!-- iCheck -->
<script src="{% static 'dash/js/plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{% static 'dash/js/AdminLTE/app.js' %}" type="text/javascript"></script>
<script src="{% static 'dash/js/AdminLTE/custom.js' %}" type="text/javascript"></script>
{% if messages %}
    <script>
        {% for message in messages %}
            alert("{{ message }}")
        {% endfor %}
    </script>
{% endif %}
<script>
    function loading() {
        var div = document.getElementById('responses')
        div.innerHTML = div.innerHTML + "<div class='overlay'></div> <div class='loading-img'></div>"
    }
</script>
</body>
</html>

django/templates/dashboard/view_class.html
{% extends 'dashboard/layout.html' %}

{% block content %}


    <!-- top row -->
    <div class="row">
        <div class="col-xs-12 connectedSortable">

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-8 connectedSortable">

            <div class="box box-danger">
                <div class="box-header">
                    <i class="fa fa-cloud"></i>

                    <h3 class="box-title">Submit to an Assignment</h3>

                    <div class="pull-right box-tools">
                        <button class="btn btn-danger btn-sm" data-widget='collapse' data-toggle="tooltip"
                                title="Collapse"><i class="fa fa-minus"></i></button>
                    </div>
                    {% if not request.user.is_authenticated %}
                        <div class="pull-right box-tools"><p class="text">You must be logged in to submit.</p></div>
                    {% endif %}
                </div>
                <!-- /.box-header -->
                <form role="form" id="post-form" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="subject_id" id="subject_id" value="{{ subject.id }}"/>

                    <div class="box-body no-padding">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="box-body">
                                    <div class="form-group col-md-7 col-sm-12">
                                        <label for="submit-username">Email</label>
                                        <input type="text" class="form-control quickclear" required="required"
                                               id="submit-username"
                                               name="submit-username" maxlength="25"
                                               value="{{ request.user.email }}">
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="submit-name">Name for Leaderboard</label>
                                        <input type="text" class="form-control quickclear" required="required"
                                               id="submit-name"
                                               name="submit-name" maxlength="25"
                                               value="{{ request.user.username }}">
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="submit-password">Your Account Password</label>
                                        <input type="password" class="form-control quickclear" required="required"
                                               id="submit-password" name="submit-password"
                                               placeholder="Password">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="docfile">File input</label>
                                        <input type="file" name="docfile" id="docfile" required="required">

                                        <p class="help-block">The system will only select a ZIP or tar file</p>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="homework">Homework to Submit to</label>
                                        <select class="form-control" id="assignment" required="required"
                                                name="assignment">
                                            {% for assignment in subject.assignments.all %}
                                                <option value="{{ assignment.id }}">{{ assignment.name }}
                                                    - {{ assignment.due_on }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row - inside box -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->

            <!-- Primary box -->
            <div class="box box-solid box-primary" id="responses">
                <div class="box-header">
                    <h3 class="box-title">Submission Response</h3>

                    <div class="box-tools pull-right">
                        <button class="btn btn-primary btn-sm" id="response" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <p id="response-text">There are no results to show currently.</p>
                </div>
                <!-- /.box-body -->
                <!-- Loading (remove the following to stop the loading)-->

            </div>
            <!-- /.box -->

        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        <section class="col-lg-4 connectedSortable">
            <div class="box box-primary">
                <div class="box-header">
                    <div class="pull-right box-tools">
                        {{ latest.name }}
                    </div>
                    <i class="fa fa-trophy"></i>

                    <h3 class="box-title">
                        Leaderboards
                    </h3>
                </div>
                <div class="box-body no-padding">
                    <div class="table-responsive">
                        <!-- .table - Uses sparkline charts-->
                        <table class="table table-striped">
                            <tr>
                                <th>Place</th>
                                <th>Codename</th>
                                <th>Grade</th>
                                <th>Efficiency</th>
                            </tr>
                            {% for submission in latest.best_submissions %}
                                <tr>
                                    <td>{{ forloop.counter }}.</td>
                                    <td>
                                        {{ submission.anon_name }}
                                    </td>
                                    <td>{{ submission.grade }}</td>
                                    <td>{{ submission.efficiency }} sec</td>
                                </tr>
                            {% endfor %}
                        </table>
                        <!-- /.table -->
                    </div>
                </div>
                <!-- /.box-body-->
                <div class="box-footer">
                    {% if latest %}
                        <a href="{% url 'dashboard:report' assignment=latest.id %}">
                    {% endif %}
                    <button class="btn btn-warning"><i class="fa fa-bug"></i> Report Bug</button>
                    </a>
                </div>
            </div>
            <!-- /.box -->

        </section>
        <!-- right col -->
    </div><!-- /.row (main row) -->

{% endblock %}